language: python

env:
  - LUA="lua=5.1" FMT="" JSON=""
  - LUA="lua=5.1" FMT="lcf" JSON=""
  - LUA="lua=5.1" FMT="formatter" JSON=""
  - LUA="lua=5.2" FMT="" JSON=""
  - LUA="lua=5.3" FMT="" JSON=""
  - LUA="lua=5.3" FMT="lcf" JSON=""
  - LUA="lua=5.4" FMT="" JSON=""
  - LUA="luajit=2.1" FMT="" JSON=""
  - LUA="luajit=2.1" FMT="" JSON="lua-cjson"

cache:
    directories:
        - lua_install

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PWD/lua_install/bin:$PATH # Add directory with all installed binaries to PATH

install:
  - luarocks install --only-deps spec/test-scm-0.rockspec
  - luarocks install --only-deps lua-lsp-scm-0.rockspec
  - luarocks install $FMT || true
  - luarocks install $JSON || true

script:
  - luacheck -ur .
  - busted --verbose --coverage

after_success:
  - "luacov-coveralls --include '^%./lua%-lsp' --exclude '^%./lua%-lsp/lua%-parser'"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
